parameters:
#    noxlogic_feed.example.class: Noxlogic\FeedBundle\Example

services:
#    noxlogic_feed.example:
#        class: %noxlogic_feed.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
